import React from 'react';
import { useApp } from '../../context/AppContext';
import { CheckCircle2, Printer, Share2, X, Download, ShieldCheck } from 'lucide-react';

export const ReceiptModal = () => {
  const { modals, closeModal, lastReceipt, activeAppointment, quickGuideToRoom, t } = useApp();

  if (!modals.receipt || !lastReceipt) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-overlay" onClick={() => closeModal('receipt')}>
      <div className="modal-content receipt-modal" onClick={e => e.stopPropagation()} role="dialog" aria-modal="true" aria-labelledby="receipt-title">
        <div className="modal-header print-hide">
          <div className="title-with-icon">
            <div className="icon-badge emerald">
              <CheckCircle2 size={24} />
            </div>
            <div>
              <h2 id="receipt-title">{t('paymentSuccessTitle')}</h2>
              <span className="subtitle-badge">Official Consultation Tax Receipt</span>
            </div>
          </div>
          <button className="close-btn" onClick={() => closeModal('receipt')} aria-label="Close">
            <X size={20} />
          </button>
        </div>

        <div className="receipt-paper" id="printable-receipt">
          <div className="receipt-brand-header">
            <div className="receipt-logo">
              <h3>Helo<span>Doc</span></h3>
              <p>National Telehealth & Hospital Network</p>
            </div>
            <div className="receipt-meta">
              <span className="receipt-no">{lastReceipt.receiptNumber}</span>
              <span className="receipt-date">{lastReceipt.timestamp}</span>
            </div>
          </div>

          <div className="receipt-token-banner">
            <span className="token-label">{t('tokenGenerated')}</span>
            <span className="token-value">{lastReceipt.tokenNumber || activeAppointment.token}</span>
            <span className="token-room">{lastReceipt.doctorName} • {lastReceipt.room}</span>
          </div>

          <div className="receipt-details-table">
            <div className="receipt-row">
              <span>Patient Name:</span>
              <strong>{lastReceipt.patientName}</strong>
            </div>
            <div className="receipt-row">
              <span>Doctor / Department:</span>
              <span>{lastReceipt.doctorName} ({lastReceipt.specialty})</span>
            </div>
            <div className="receipt-row">
              <span>Transaction ID:</span>
              <span className="font-mono">{lastReceipt.transactionId}</span>
            </div>
            <div className="receipt-row">
              <span>Payment Mode:</span>
              <span>{lastReceipt.paymentMethod} ({lastReceipt.mode})</span>
            </div>
            <div className="receipt-row">
              <span>GSTIN / Tax Registration:</span>
              <span className="font-mono">{lastReceipt.gstin}</span>
            </div>
            <div className="receipt-divider"></div>
            <div className="receipt-row total-paid-row">
              <span>Amount Paid:</span>
              <span className="paid-amount">₹{lastReceipt.amount} (Paid ✓)</span>
            </div>
          </div>

          <div className="receipt-footer-seal">
            <ShieldCheck size={16} className="text-emerald-600 inline mr-1" />
            <span>Digital Verified Receipt • Generated by HeloDoc Payment Abstraction Engine</span>
          </div>
        </div>

        <div className="modal-footer print-hide actions-split">
          <button
            type="button"
            className="secondary-btn"
            onClick={handlePrint}
          >
            <Printer size={18} /> Print / PDF
          </button>

          <button
            type="button"
            className="primary-btn guide-action-btn"
            onClick={() => {
              closeModal('receipt');
              quickGuideToRoom(activeAppointment.room, activeAppointment.floor);
            }}
          >
            👉 {t('openMapNav')}
          </button>
        </div>
      </div>
    </div>
  );
};
